export const SOURCES = [
  { group: "Medium", category: "Data Engineering", url: "https://medium.com/feed/tag/data-engineering" },
  { group: "Medium", category: "Data Engineering", url: "https://medium.com/feed/tag/analytics-engineering" },
  { group: "Medium", category: "Data Leadership", url: "https://medium.com/feed/tag/data-leadership" },
  { group: "Medium", category: "Data Leadership", url: "https://medium.com/feed/tag/data-strategy" },

  { group: "Substack", category: "Data Engineering", url: "https://seattledataguy.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://dataengineeringweekly.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://roundup.getdbt.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://benn.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://joshwills.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://mikkeldengsoe.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://datagibberish.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://theanalyticsengineer.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://analyticsengineeringroundup.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://blog.det.life/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://dataengweekly.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://datatalksclub.substack.com/feed" },
  { group: "Substack", category: "Data Engineering", url: "https://motherduck.com/blog/rss.xml" },

  { group: "Substack", category: "Data Leadership", url: "https://locallyoptimistic.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://moderndata101.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://dataproducts.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://datateams.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://dataleadershipweekly.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://benn.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://decision.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://datacreation.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://datawithdanny.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://datahappy.substack.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://roundup.getdbt.com/feed" },
  { group: "Substack", category: "Data Leadership", url: "https://locallyoptimistic.com/rss/" },

  { group: "Other", category: "Data Leadership", url: "https://www.nicolaaskham.com/blog?format=rss" },
  { group: "Other", category: "Data Leadership", url: "https://www.eckerson.com/rss.xml" },
  { group: "Other", category: "Data Leadership", url: "https://tdan.com/feed" },
  { group: "Other", category: "Data Engineering", url: "https://www.getdbt.com/blog/rss.xml" },
  { group: "Other", category: "Data Engineering", url: "https://airflow.apache.org/blog/feed.xml" },
  { group: "Other", category: "Data Engineering", url: "https://www.snowflake.com/blog/feed/" },
  { group: "Other", category: "Data Engineering", url: "https://cloud.google.com/blog/products/data-analytics/rss" },
  { group: "Other", category: "Data Engineering", url: "https://www.databricks.com/blog/feed" }
];
